name: Flutter CI/CD with Telegram

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build and Deploy APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.1'

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Build APK
        run: flutter build apk --release

      - name: Get App Version
        id: version
        run: echo "VERSION=$(grep '^version:' pubspec.yaml | awk '{print $2}')" >> $GITHUB_ENV

      - name: Upload APK to Telegram
        uses: appleboy/telegram-action@master
        with:
          token: 7335164771:AAHrrOgdv1zcub8vAyTunH-2TP1ur5UOWqg
          to: 5381246894
          document: build/app/outputs/flutter-apk/app-release.apk
          caption: |
            📦 *app-release-${{ env.VERSION }}.apk*
            *Repository:* `${{ github.repository }}`
            *Commit:* `${{ github.sha }}`
            *Message:* `${{ github.event.head_commit.message }}`
            *Date:* `${{ github.event.head_commit.timestamp }}`
          format: markdown
